import type { App, Component, Plugin } from 'vue';
import * as Ui from '@aditify/ui';
import {
  ArchiveRestore,
  BadgeCheck,
  BrushCleaning,
  CloudDownload,
  Container,
  Download,
  DownloadCloud,
  Eraser,
  History,
  Network,
  Plus,
  RefreshCw,
  Settings2,
  Trash2,
  Upload,
  X,
} from '@lucide/vue';

const componentNames = [
  'Accordion',
  'AccordionContent',
  'AccordionItem',
  'AccordionTrigger',
  'Alert',
  'AlertDescription',
  'AlertTitle',
  'Badge',
  'Button',
  'ButtonGroup',
  'Card',
  'CardAction',
  'CardContent',
  'CardDescription',
  'CardFooter',
  'CardHeader',
  'CardTitle',
  'Checkbox',
  'Collapsible',
  'CollapsibleContent',
  'CollapsibleTrigger',
  'Dialog',
  'DialogContent',
  'DialogDescription',
  'DialogFooter',
  'DialogHeader',
  'DialogTitle',
  'DropdownMenu',
  'DropdownMenuContent',
  'DropdownMenuItem',
  'DropdownMenuSeparator',
  'DropdownMenuTrigger',
  'Field',
  'FieldDescription',
  'FieldGroup',
  'FieldLabel',
  'Input',
  'InputGroup',
  'InputGroupAddon',
  'InputGroupButton',
  'InputGroupInput',
  'Popover',
  'PopoverContent',
  'PopoverTrigger',
  'Progress',
  'RadioGroup',
  'RadioGroupItem',
  'Select',
  'SelectContent',
  'SelectItem',
  'SelectTrigger',
  'SelectValue',
  'Separator',
  'Spinner',
  'Switch',
  'Table',
  'TableBody',
  'TableCell',
  'TableEmpty',
  'TableHead',
  'TableHeader',
  'TableRow',
  'Tabs',
  'TabsContent',
  'TabsList',
  'TabsTrigger',
  'TagsInput',
  'TagsInputInput',
  'TagsInputItem',
  'TagsInputItemDelete',
  'TagsInputItemText',
  'Textarea',
  'Tooltip',
  'TooltipContent',
  'TooltipProvider',
  'TooltipTrigger',
] as const;

export function registerNativeUi(app: App): void {
  for (const name of componentNames)
    app.component(name, Ui[name] as Component);

  for (const [name, component] of Object.entries({
    ArchiveRestore,
    BadgeCheck,
    BrushCleaning,
    CloudDownload,
    Container,
    Download,
    DownloadCloud,
    Eraser,
    History,
    Network,
    Plus,
    RefreshCw,
    Settings2,
    Trash2,
    Upload,
    X,
  }))
    app.component(name, component);
}

export const nativeUiPlugin: Plugin = { install: registerNativeUi };
